# Generated by Django 2.2.7 on 2020-06-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('house_rent', models.IntegerField()),
                ('medical', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('other', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('over_time', models.IntegerField()),
                ('deduction', models.IntegerField()),
                ('Salary_disburse', models.IntegerField()),
                ('Salary_disburse_month', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
