# Generated by Django 2.2.7 on 2020-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20200612_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='Salary_disburse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='deduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='house_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='medical',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='other',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='over_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='transport',
            field=models.IntegerField(default=0),
        ),
    ]
