# Generated by Django 2.2.7 on 2020-07-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_auto_20200709_1620'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salary',
            table='salaries',
        ),
    ]
