# Generated by Django 2.2.7 on 2020-06-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deptbranch',
            table='DeptBranch',
        ),
    ]
