# Generated by Django 2.2.7 on 2020-07-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept_branch', '0003_auto_20200618_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch', unique=True),
        ),
        migrations.AlterField(
            model_name='deptbranch',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', unique=True),
        ),
    ]
