# Generated by Django 2.2.7 on 2020-06-12 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_branch.DeptBranch'),
        ),
    ]
