# Generated by Django 2.2.7 on 2020-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(verbose_name='joining date')),
                ('end_date', models.DateTimeField(verbose_name='joining date')),
                ('budget', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
