# Generated by Django 2.2.7 on 2020-07-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projec_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project',
            new_name='project_id',
        ),
    ]
