# Generated by Django 2.2.7 on 2020-07-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projec_detail', '0003_auto_20200708_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project_id',
            new_name='project',
        ),
    ]
