# Generated by Django 2.2.7 on 2020-07-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projec_detail', '0004_auto_20200708_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
