# Generated by Django 2.2.7 on 2020-07-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projec_detail', '0006_auto_20200708_1846'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectdetail',
            table='project_details',
        ),
    ]
