# Generated by Django 2.2.7 on 2020-07-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_groups'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
