version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=hrm
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hrm
    ports:
      - 5430:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6378:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8080:8000
    environment:
      - DB_HOST=db
      - DB_USER=hrm
      - DB_PASS=123456
      - DB_PORT=5432
      - DB_NAME=hrm
      - DEBUG=True
      - SECRET_KEY=^&0zxq-&3)fqv^p+(^yp^@r5#0q!(5t1u1-zl70tiy1@f*wm0r
      - REDIS_HOST=redis
      
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
      - FLOWER_PORT=8888
    ports:
      - 5555:8888
    depends_on:
      - celery-worker

  celery-worker:
      build: .
      links:
        - db:db
        - redis:redis
      command: bash -c "cd src/ && rm -rf celerybeat.pid && celery -A hrm.celery worker -l info --concurrency=4"
      depends_on:
        - db
        - redis
      volumes:
        - ./src:/app/src
      environment:
        - DB_HOST=db
        - DB_USER=hrm
        - DB_PASS=123456
        - DB_PORT=5432
        - DB_NAME=hrm
        - DEBUG=True
        - SECRET_KEY=^&0zxq-&3)fqv^p+(^yp^@r5#0q!(5t1u1-zl70tiy1@f*wm0r
        - REDIS_HOST=redis

  celery-beat:
      build: .
      links:
        - db:db
        - redis:redis
      command: bash -c "cd src/ && celery -A hrm.celery beat -l info"
      depends_on:
        - db
        - redis
        
      volumes:
        - ./src:/app/src
      
      environment:
        - DB_HOST=db
        - DB_USER=hrm
        - DB_PASS=123456
        - DB_PORT=5432
        - DB_NAME=hrm
        - DEBUG=True
        - SECRET_KEY=^&0zxq-&3)fqv^p+(^yp^@r5#0q!(5t1u1-zl70tiy1@f*wm0r
        - REDIS_HOST=redis

