version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=hrm
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hrm
    ports:
      - 5430:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6377:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8080:8000
    environment:
      - DB_HOST=db
      - DB_USER=hrm
      - DB_PASS=123456
      - DB_PORT=5432
      - DB_NAME=hrm
      - DEBUG=True
      - SECRET_KEY=^&0zxq-&3)fqv^p+(^yp^@r5#0q!(5t1u1-zl70tiy1@f*wm0r
